# Generated by Django 3.2.13 on 2023-09-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'картинку', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
