# Generated by Django 3.2.13 on 2023-09-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_add', models.DateTimeField()),
                ('document_type', models.CharField(choices=[('CD', 'Учредительный документ'), ('GM', 'Общее собрание'), ('BW', 'Работа правления'), ('СС', 'Работа учредительной комиссии'), ('FS', 'Финансовая отчетность')], default='CD', max_length=2)),
            ],
            options={
                'verbose_name': 'директорий',
                'verbose_name_plural': 'Директории',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_add', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.directory')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
