# Generated by Django 3.2.13 on 2023-09-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Учредительный документ'), (2, 'Общее собрание'), (3, 'Работа правления'), (4, 'Работа учредительной комиссии'), (5, 'Финансовая отчетность')], primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('Учредительный документ', 'Учредительный документ'), ('Общее собрание', 'Общее собрание'), ('Работа правления', 'Работа правления'), ('Работа учредительной комиссии', 'Работа учредительной комиссии'), ('Финансовая отчетность', 'Финансовая отчетность')], max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'категорий',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_add', models.DateTimeField()),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.category')),
            ],
            options={
                'verbose_name': 'директорий',
                'verbose_name_plural': 'Директории',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_add', models.DateTimeField()),
                ('file', models.FileField(upload_to='documents/')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.directory')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
