# Generated by Django 3.2.13 on 2023-09-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name': 'директорию', 'verbose_name_plural': 'Директории'},
        ),
    ]
